### PR TITLE
Change Configure to fix issues with constant blink

### PR DESCRIPTION
**Pull request by miriad**
Change configure method on centralite keypads to more closely match SmartThings official DTH for centralite sensors (Used motion sensor as the base).

Fixes configure issues (constant blink) on Iris keypad (tested)

### CODE REVIEW

**Comment by mitchpond** [comment]
According to the Ember documentation and examples that I've seen, "send" is not required after "zdo bind", so I'm not sure that's correct. I didn't see that in the ST handlers either. I'll need to check the increase in delays with the Xfinity version as well. I had issues with configuration when delays were set too high.

**Comment by miriad** [comment]
Looking back at the device handlers I referenced, I think you're right. Not sure where I got adding the send in from. Perhaps a little over-zealous on the copy.

I'm not sure the higher delays were important, I think they were just testing random bits for me. 

I can probably make an updated patch tomorrow without the sends after the binds, and back down to the lower delays, and see if it still works. If so, I'll update the pull request.

**Comment by miriad** [comment]
Ok, new patch here. Better delays on the timing.

**Comment by mitchpond** [comment]
Seems to test OK with mine.

**Pull request merged**
